#!/usr/bin/env bash

folder_name=$3

uid=$(( ( RANDOM )  + 10000 ))

#echo "127.0.0.1 $(hostname)" >> /etc/hosts

groupadd code
useradd -u "$uid" -G code -d "/home/codecube" -m codecube 

chgrp code $folder_name
chmod -R g+r $folder_name
#chmod a+x /run_test_no_sandbox

cd $folder_name
sudo -u codecube python3 -m grader $1 $2