#!/usr/bin/env bash

folder_name=$3

uid=$(( ( RANDOM )  + 10000 ))

#echo "127.0.0.1 $(hostname)" >> /etc/hosts

groupadd code
useradd -u "$uid" -G code -d "/home/codecube" -m codecube

real_folder='/real-'
real_folder+=$(( ( RANDOM )  + 10000 ))
#echo $real_folder

cp -r $folder_name $real_folder
cd $real_folder
chmod -R 0755 .
sudo -u codecube python3 -m grader $1 $2