#!/usr/bin/env bash

folder_name=$3

uid=$(( ( RANDOM )  + 10000 ))

#echo "127.0.0.1 $(hostname)" >> /etc/hosts

groupadd code
useradd -u "$uid" -G code -d "/home/codecube" -m codecube

cd $folder_name
chmod -R 0755 .
sudo -u codecube python3 -m grader $1 $2