#!/usr/bin/env python3
"""
Script that accepts two paths and index - tester path and solution path

"""

from os import path
from sys import argv, exit

if len(argv) < 4:
    print("Usage: run_test_no_sandbox <tester-path> <solution-path> <test-name>")
    exit(1)

from grader import execution_base