#!/usr/bin/env python3

from os import path
from sys import argv, exit
from grader import execution_base
from grader.asset_management import AssetFolder

if len(argv) < 4:
    print("Usage: run_test <tester-path> <solution-path> <test-name> (<asset_dir>)")
    exit(1)

# assume all files reside in same directory
asset_files = path.dirname(argv[1])

with AssetFolder(argv[1], argv[2], [asset_files]) as assets:
    execution_base.call_test_function(argv[3], assets.tester_path, assets.solution_path)