#!/usr/bin/env python3

import sys
import string
import random
from grader import code_runner
from os import path


def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


def construct_cmd(mounted_dir, code_dir, *rest):
    volume_cmd = '{}:{}:ro'.format(mounted_dir, code_dir)
    cmd = [
        'docker', 'run', 
        '-v', volume_cmd,
        'macobo/python-grader-sandbox'
    ]
    cmd.extend(rest)
    return cmd

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: run_tests_docker_sandbox <tester-path> <solution-path>")
        sys.exit(1)

    tester_path, solution_path = map(path.abspath, sys.argv[1:3])
    code_dir = "/code-{}".format(id_generator())

    folder = path.dirname(tester_path)
    grader_args = [
        path.join(code_dir, path.basename(tester_path)),
        path.join(code_dir, path.basename(solution_path)),
        code_dir
    ]

    full_cmd = construct_cmd(folder, code_dir, *grader_args)
    exitcode, stdout, stderr = code_runner.call_command(full_cmd)

    print(stdout)
    print(stderr, file=sys.stderr)
    sys.exit(exitcode)
